### ISSUE TITLE
[Rolodex] Add Email field support for Contacts

### ISSUE THREAD

**Issue by prashant3863** [shovelers/network-monorepo#19]
Context
* As a user, my primary form of contact is email. I want to be able to see the email addresses present in my contacts or add emails to the missing contacts So that I can easily reach out to the contacts I search via Rolodex

Already present
* Apple and Google import already pulls this value and populate it for each `Person` in the ContactList

Work
*  Add Email as a field in the `Contact` in Rolodex
*  Contact Edit modal should show `email` as a field, showing value if present and empty if absent
* Contact edit should support update to emails for a contact
* Search should look through Email field as well

**Comment by 200016harshjain** [comment]
<img width="1317" alt="image" src="https://github.com/shovelers/network-monorepo/assets/44161491/829f2758-c3b3-42b8-a7ab-96a920ef2c48">

1. For 'Work - 1' - you mean email should be present in this view for each contact? Effectively {Name, Email, Tag}?

**Comment by prashant3863** [comment]
Yes, email as a field in this list view. so the columns of the table become {Name, Email, Tag, Edit button}
